const fs = require('fs');
const path = require('path');

const seedsDir = path.join(__dirname, 'temp_seeds');
const outputFile = path.join(__dirname, 'prisma', 'seed-data.ts');

async function mergeSeeds() {
  const files = fs.readdirSync(seedsDir).filter(f => f.endsWith('.json'));
  let allWords = [];
  
  for (const file of files) {
    try {
      const content = fs.readFileSync(path.join(seedsDir, file), 'utf-8');
      const data = JSON.parse(content);
      if (Array.isArray(data)) {
        allWords = allWords.concat(data);
      }
    } catch (e) {
      console.error(`Error parsing ${file}:`, e);
    }
  }

  console.log(`Merged ${allWords.length} total words.`);

  // Validate fields to ensure no nulls or weird formats
  const validWords = allWords.map(w => ({
    category: String(w.category || '').trim(),
    word: String(w.word || '').trim(),
    easyHint: String(w.easyHint || '').trim(),
    mediumHint: String(w.mediumHint || '').trim(),
    hardHint: String(w.hardHint || '').trim(),
  })).filter(w => w.category && w.word);

  const fileContent = `// =============================================================================
// EzyImposter — Word Database (Seed Data)
// Massive Expansion - Generated by Subagents
// =============================================================================

export interface WordEntry {
  category: string;
  word: string;
  easyHint: string;
  mediumHint: string;
  hardHint: string;
}

export const wordDatabase: WordEntry[] = ${JSON.stringify(validWords, null, 2)};
`;

  fs.writeFileSync(outputFile, fileContent);
  console.log(`Wrote to ${outputFile}`);
}

mergeSeeds();
