// =============================================================================
// EzyImposter — Word Database (Seed Data)
// =============================================================================
// Each entry has:
//   - category : grouping label
//   - word     : the SECRET word shown to regular players
//   - easyHint : almost gives it away (closely related)
//   - mediumHint : broader relation / category clue
//   - hardHint : loose, tricky connection — tough for the imposter
// =============================================================================

export interface WordEntry {
  category: string;
  word: string;
  easyHint: string;
  mediumHint: string;
  hardHint: string;
}

export const wordDatabase: WordEntry[] = [
  // ===========================================================================
  // 1. BOLLYWOOD MOVIES
  // ===========================================================================
  {
    category: 'Bollywood Movies',
    word: 'Sholay',
    easyHint: 'Deewar',
    mediumHint: 'Classic Action Film',
    hardHint: 'Flames',
  },
  {
    category: 'Bollywood Movies',
    word: 'Dangal',
    easyHint: 'Sultan',
    mediumHint: 'Wrestling Movie',
    hardHint: 'Mat',
  },
  {
    category: 'Bollywood Movies',
    word: '3 Idiots',
    easyHint: 'PK',
    mediumHint: 'College Comedy',
    hardHint: 'All Is Well',
  },
  {
    category: 'Bollywood Movies',
    word: 'DDLJ',
    easyHint: 'Kuch Kuch Hota Hai',
    mediumHint: 'Romantic Train Journey',
    hardHint: 'Mustard Fields',
  },
  {
    category: 'Bollywood Movies',
    word: 'Lagaan',
    easyHint: 'Swades',
    mediumHint: 'Cricket Period Film',
    hardHint: 'Tax',
  },
  {
    category: 'Bollywood Movies',
    word: 'Gangs of Wasseypur',
    easyHint: 'Satya',
    mediumHint: 'Crime Saga',
    hardHint: 'Coal Mines',
  },
  {
    category: 'Bollywood Movies',
    word: 'Zindagi Na Milegi Dobara',
    easyHint: 'Dil Chahta Hai',
    mediumHint: 'Road Trip Film',
    hardHint: 'Tomato Festival',
  },
  {
    category: 'Bollywood Movies',
    word: 'Bajrangi Bhaijaan',
    easyHint: 'Ek Tha Tiger',
    mediumHint: 'Cross-Border Story',
    hardHint: 'Monkey God',
  },
  {
    category: 'Bollywood Movies',
    word: 'Gully Boy',
    easyHint: 'Zoya Akhtar',
    mediumHint: 'Mumbai Rap Film',
    hardHint: 'Dharavi Beats',
  },
  {
    category: 'Bollywood Movies',
    word: 'Andhadhun',
    easyHint: 'Badlapur',
    mediumHint: 'Thriller About Blindness',
    hardHint: 'Piano Keys',
  },
  {
    category: 'Bollywood Movies',
    word: 'Padmaavat',
    easyHint: 'Bajirao Mastani',
    mediumHint: 'Rajput Epic',
    hardHint: 'Jauhar',
  },
  {
    category: 'Bollywood Movies',
    word: 'Queen',
    easyHint: 'English Vinglish',
    mediumHint: 'Solo Honeymoon Film',
    hardHint: 'Paris Discovery',
  },
  {
    category: 'Bollywood Movies',
    word: 'Barfi',
    easyHint: 'Iqbal',
    mediumHint: 'Deaf-Mute Love Story',
    hardHint: 'Sweet Treat',
  },
  {
    category: 'Bollywood Movies',
    word: 'Rang De Basanti',
    easyHint: 'Yuva',
    mediumHint: 'Youth Revolution Film',
    hardHint: 'Saffron Color',
  },
  {
    category: 'Bollywood Movies',
    word: 'Dilwale Dulhania Le Jayenge',
    easyHint: 'Mohabbatein',
    mediumHint: 'NRI Romance',
    hardHint: 'Cowbell',
  },
  {
    category: 'Bollywood Movies',
    word: 'Mughal-E-Azam',
    easyHint: 'Mother India',
    mediumHint: 'Historical Royal Drama',
    hardHint: 'Feather Fan',
  },
  {
    category: 'Bollywood Movies',
    word: 'Kabhi Khushi Kabhie Gham',
    easyHint: 'Kabhi Alvida Naa Kehna',
    mediumHint: 'Family Drama',
    hardHint: 'Poo',
  },
  {
    category: 'Bollywood Movies',
    word: 'Chak De India',
    easyHint: 'Dangal',
    mediumHint: 'Women Hockey Film',
    hardHint: 'Seventy Minutes',
  },
  {
    category: 'Bollywood Movies',
    word: 'Dil Chahta Hai',
    easyHint: 'ZNMD',
    mediumHint: 'Goa Friendship Film',
    hardHint: 'Fort Painting',
  },
  {
    category: 'Bollywood Movies',
    word: 'Pushpa',
    easyHint: 'KGF',
    mediumHint: 'Smuggling Action Film',
    hardHint: 'Red Sandalwood',
  },
  {
    category: 'Bollywood Movies',
    word: 'RRR',
    easyHint: 'Baahubali',
    mediumHint: 'Period Action Epic',
    hardHint: 'Naatu Naatu',
  },
  {
    category: 'Bollywood Movies',
    word: 'Jawan',
    easyHint: 'Pathaan',
    mediumHint: 'Action Thriller 2023',
    hardHint: 'Bald Disguise',
  },
  {
    category: 'Bollywood Movies',
    word: 'Taare Zameen Par',
    easyHint: '3 Idiots',
    mediumHint: 'Dyslexia Film',
    hardHint: 'Crayons',
  },
  {
    category: 'Bollywood Movies',
    word: 'Hera Pheri',
    easyHint: 'Phir Hera Pheri',
    mediumHint: 'Comedy Trio',
    hardHint: '25 Din Mein Paisa Double',
  },
  {
    category: 'Bollywood Movies',
    word: 'Omkara',
    easyHint: 'Haider',
    mediumHint: 'Shakespeare Adaptation',
    hardHint: 'Green-Eyed Monster',
  },

  // ===========================================================================
  // 2. BOLLYWOOD ACTORS
  // ===========================================================================
  {
    category: 'Bollywood Actors',
    word: 'Shah Rukh Khan',
    easyHint: 'King Khan',
    mediumHint: 'Mannat',
    hardHint: 'Open Arms Pose',
  },
  {
    category: 'Bollywood Actors',
    word: 'Aamir Khan',
    easyHint: 'Mr. Perfectionist',
    mediumHint: 'One Film A Year',
    hardHint: 'Ghajini Abs',
  },
  {
    category: 'Bollywood Actors',
    word: 'Amitabh Bachchan',
    easyHint: 'Big B',
    mediumHint: 'Angry Young Man',
    hardHint: 'Baritone Voice',
  },
  {
    category: 'Bollywood Actors',
    word: 'Deepika Padukone',
    easyHint: 'Ranveer\'s Wife',
    mediumHint: 'Om Shanti Om Debut',
    hardHint: 'Badminton Champion\'s Daughter',
  },
  {
    category: 'Bollywood Actors',
    word: 'Salman Khan',
    easyHint: 'Bhai',
    mediumHint: 'Being Human',
    hardHint: 'Shirtless Entry',
  },
  {
    category: 'Bollywood Actors',
    word: 'Ranveer Singh',
    easyHint: 'Deepika\'s Husband',
    mediumHint: 'Band Baaja Baaraat Debut',
    hardHint: 'Outrageous Outfits',
  },
  {
    category: 'Bollywood Actors',
    word: 'Alia Bhatt',
    easyHint: 'Ranbir\'s Wife',
    mediumHint: 'Student of the Year',
    hardHint: 'Mahesh Bhatt\'s Daughter',
  },
  {
    category: 'Bollywood Actors',
    word: 'Hrithik Roshan',
    easyHint: 'Greek God',
    mediumHint: 'Kaho Naa Pyaar Hai',
    hardHint: 'Extra Thumb',
  },
  {
    category: 'Bollywood Actors',
    word: 'Akshay Kumar',
    easyHint: 'Khiladi',
    mediumHint: 'Canadian Passport',
    hardHint: '4 AM Wake Up',
  },
  {
    category: 'Bollywood Actors',
    word: 'Priyanka Chopra',
    easyHint: 'Desi Girl',
    mediumHint: 'Miss World',
    hardHint: 'Nick Jonas Wife',
  },
  {
    category: 'Bollywood Actors',
    word: 'Ranbir Kapoor',
    easyHint: 'Alia\'s Husband',
    mediumHint: 'Kapoor Dynasty',
    hardHint: 'Saawariya Debut',
  },
  {
    category: 'Bollywood Actors',
    word: 'Katrina Kaif',
    easyHint: 'Vicky\'s Wife',
    mediumHint: 'British-Indian Actress',
    hardHint: 'Kay Beauty',
  },
  {
    category: 'Bollywood Actors',
    word: 'Rajkummar Rao',
    easyHint: 'Patralekhaa\'s Husband',
    mediumHint: 'Method Actor',
    hardHint: 'Citylights',
  },
  {
    category: 'Bollywood Actors',
    word: 'Ayushmann Khurrana',
    easyHint: 'Vicky Donor',
    mediumHint: 'Singing Actor',
    hardHint: 'Roadies Winner',
  },
  {
    category: 'Bollywood Actors',
    word: 'Vidya Balan',
    easyHint: 'Kahaani',
    mediumHint: 'Saree Queen',
    hardHint: 'Dirty Picture',
  },
  {
    category: 'Bollywood Actors',
    word: 'Irrfan Khan',
    easyHint: 'Paan Singh Tomar',
    mediumHint: 'Hollywood Crossover',
    hardHint: 'Life of Pi',
  },
  {
    category: 'Bollywood Actors',
    word: 'Nawazuddin Siddiqui',
    easyHint: 'Sacred Games',
    mediumHint: 'Gangs of Wasseypur',
    hardHint: 'NSD Graduate',
  },
  {
    category: 'Bollywood Actors',
    word: 'Kangana Ranaut',
    easyHint: 'Queen',
    mediumHint: 'Tanu Weds Manu',
    hardHint: 'Controversy Queen',
  },
  {
    category: 'Bollywood Actors',
    word: 'Varun Dhawan',
    easyHint: 'David Dhawan\'s Son',
    mediumHint: 'Judwaa 2',
    hardHint: 'Student of the Year',
  },
  {
    category: 'Bollywood Actors',
    word: 'Kartik Aaryan',
    easyHint: 'Bhool Bhulaiyaa 2',
    mediumHint: 'Monologue King',
    hardHint: 'Gwalior Boy',
  },
  {
    category: 'Bollywood Actors',
    word: 'Pankaj Tripathi',
    easyHint: 'Mirzapur',
    mediumHint: 'Kaleen Bhaiya',
    hardHint: 'Hotel Management Graduate',
  },
  {
    category: 'Bollywood Actors',
    word: 'Vicky Kaushal',
    easyHint: 'Uri',
    mediumHint: 'How\'s The Josh',
    hardHint: 'Action Director\'s Son',
  },
  {
    category: 'Bollywood Actors',
    word: 'Madhuri Dixit',
    easyHint: 'Dhak Dhak Girl',
    mediumHint: 'Hum Aapke Hain Koun',
    hardHint: 'Million Dollar Smile',
  },
  {
    category: 'Bollywood Actors',
    word: 'Sridevi',
    easyHint: 'Chandni',
    mediumHint: 'First Female Superstar',
    hardHint: 'Naagin',
  },

  // ===========================================================================
  // 3. BOLLYWOOD SONGS
  // ===========================================================================
  {
    category: 'Bollywood Songs',
    word: 'Chaiyya Chaiyya',
    easyHint: 'Train Roof Dance',
    mediumHint: 'Dil Se',
    hardHint: 'AR Rahman Sufi Track',
  },
  {
    category: 'Bollywood Songs',
    word: 'Tujhe Dekha Toh',
    easyHint: 'DDLJ Love Song',
    mediumHint: 'Mustard Field Romance',
    hardHint: 'Jaana Sanam',
  },
  {
    category: 'Bollywood Songs',
    word: 'Kal Ho Naa Ho',
    easyHint: 'SRK Heartbreak Song',
    mediumHint: 'New York Balcony',
    hardHint: 'Tomorrow May Not Come',
  },
  {
    category: 'Bollywood Songs',
    word: 'Mere Sapno Ki Rani',
    easyHint: 'Aradhana',
    mediumHint: 'Jeep Song',
    hardHint: 'Kishore Kumar Classic',
  },
  {
    category: 'Bollywood Songs',
    word: 'Chamma Chamma',
    easyHint: 'China Gate',
    mediumHint: 'Item Number',
    hardHint: 'Ankle Bells',
  },
  {
    category: 'Bollywood Songs',
    word: 'Munni Badnaam',
    easyHint: 'Sheila Ki Jawani',
    mediumHint: 'Dabangg Item Song',
    hardHint: 'Ruined Reputation',
  },
  {
    category: 'Bollywood Songs',
    word: 'Tum Hi Ho',
    easyHint: 'Aashiqui 2',
    mediumHint: 'Arijit Singh Ballad',
    hardHint: 'Rain Romance',
  },
  {
    category: 'Bollywood Songs',
    word: 'Kesariya',
    easyHint: 'Brahmastra',
    mediumHint: 'Arijit Singh Wedding Song',
    hardHint: 'Saffron Color',
  },
  {
    category: 'Bollywood Songs',
    word: 'Kabhi Khushi Kabhie Gham',
    easyHint: 'K3G Title Track',
    mediumHint: 'Lata Mangeshkar Emotional',
    hardHint: 'Sometimes Joy',
  },
  {
    category: 'Bollywood Songs',
    word: 'Rang De Basanti',
    easyHint: 'Title Song',
    mediumHint: 'AR Rahman Patriotic',
    hardHint: 'Color Me Saffron',
  },
  {
    category: 'Bollywood Songs',
    word: 'Lungi Dance',
    easyHint: 'Chennai Express',
    mediumHint: 'SRK Tribute Song',
    hardHint: 'South Indian Cloth',
  },
  {
    category: 'Bollywood Songs',
    word: 'Jai Ho',
    easyHint: 'Slumdog Millionaire',
    mediumHint: 'Oscar Winner Song',
    hardHint: 'Victory Chant',
  },
  {
    category: 'Bollywood Songs',
    word: 'Dil To Pagal Hai',
    easyHint: 'SRK Madhuri Dance',
    mediumHint: 'Heart Is Crazy',
    hardHint: 'Dance Rehearsal Stage',
  },
  {
    category: 'Bollywood Songs',
    word: 'Choli Ke Peeche',
    easyHint: 'Khalnayak',
    mediumHint: '90s Controversial Song',
    hardHint: 'Behind The Blouse',
  },
  {
    category: 'Bollywood Songs',
    word: 'Bole Chudiyan',
    easyHint: 'K3G Wedding Song',
    mediumHint: 'Bangles Singing',
    hardHint: 'Family Celebration',
  },
  {
    category: 'Bollywood Songs',
    word: 'Mera Dil Bhi Kitna Pagal Hai',
    easyHint: 'Saajan',
    mediumHint: 'Kumar Sanu Classic',
    hardHint: 'Crazy Heart Confession',
  },
  {
    category: 'Bollywood Songs',
    word: 'Naatu Naatu',
    easyHint: 'RRR',
    mediumHint: 'Oscar Winning Dance',
    hardHint: 'Foot Stomping Telugu',
  },
  {
    category: 'Bollywood Songs',
    word: 'Gerua',
    easyHint: 'Dilwale',
    mediumHint: 'SRK Kajol Iceland',
    hardHint: 'Ochre Color',
  },
  {
    category: 'Bollywood Songs',
    word: 'Sapna Jahan',
    easyHint: 'Brothers',
    mediumHint: 'Sonu Nigam Inspirational',
    hardHint: 'Dream Place',
  },
  {
    category: 'Bollywood Songs',
    word: 'Maahi Ve',
    easyHint: 'Kal Ho Naa Ho',
    mediumHint: 'Wedding Celebration Song',
    hardHint: 'My Beloved',
  },
  {
    category: 'Bollywood Songs',
    word: 'Kuch Kuch Hota Hai',
    easyHint: 'Title Track SRK',
    mediumHint: 'College Love Triangle',
    hardHint: 'Something Happens',
  },
  {
    category: 'Bollywood Songs',
    word: 'Badtameez Dil',
    easyHint: 'Yeh Jawaani Hai Deewani',
    mediumHint: 'Ranbir Deepika Dance',
    hardHint: 'Naughty Heart',
  },
  {
    category: 'Bollywood Songs',
    word: 'Apna Time Aayega',
    easyHint: 'Gully Boy',
    mediumHint: 'Ranveer Rap Song',
    hardHint: 'My Time Will Come',
  },
  {
    category: 'Bollywood Songs',
    word: 'Zingaat',
    easyHint: 'Dhadak',
    mediumHint: 'High Energy Dance',
    hardHint: 'Marathi Crossover',
  },

  // ===========================================================================
  // 4. INDIAN FOOD
  // ===========================================================================
  {
    category: 'Indian Food',
    word: 'Biryani',
    easyHint: 'Pulao',
    mediumHint: 'Hyderabadi Rice Dish',
    hardHint: 'Dum Cooking',
  },
  {
    category: 'Indian Food',
    word: 'Butter Chicken',
    easyHint: 'Chicken Tikka Masala',
    mediumHint: 'Creamy Tomato Curry',
    hardHint: 'Moti Mahal Invention',
  },
  {
    category: 'Indian Food',
    word: 'Samosa',
    easyHint: 'Pakora',
    mediumHint: 'Fried Triangular Snack',
    hardHint: 'Chai Companion',
  },
  {
    category: 'Indian Food',
    word: 'Pani Puri',
    easyHint: 'Golgappa',
    mediumHint: 'Street Side Water Snack',
    hardHint: 'One Bite Explosion',
  },
  {
    category: 'Indian Food',
    word: 'Dosa',
    easyHint: 'Idli',
    mediumHint: 'South Indian Crepe',
    hardHint: 'Fermented Batter',
  },
  {
    category: 'Indian Food',
    word: 'Chole Bhature',
    easyHint: 'Puri Sabzi',
    mediumHint: 'Punjabi Fried Bread Curry',
    hardHint: 'Delhi Breakfast',
  },
  {
    category: 'Indian Food',
    word: 'Gulab Jamun',
    easyHint: 'Rasgulla',
    mediumHint: 'Fried Sweet Balls',
    hardHint: 'Rose Water Syrup',
  },
  {
    category: 'Indian Food',
    word: 'Paneer Tikka',
    easyHint: 'Chicken Tikka',
    mediumHint: 'Grilled Cottage Cheese',
    hardHint: 'Tandoor Cubes',
  },
  {
    category: 'Indian Food',
    word: 'Vada Pav',
    easyHint: 'Pav Bhaji',
    mediumHint: 'Mumbai Street Burger',
    hardHint: 'Potato In A Bun',
  },
  {
    category: 'Indian Food',
    word: 'Jalebi',
    easyHint: 'Imarti',
    mediumHint: 'Spiral Sweet',
    hardHint: 'Orange Pretzel',
  },
  {
    category: 'Indian Food',
    word: 'Tandoori Chicken',
    easyHint: 'Grilled Chicken',
    mediumHint: 'Red Marinated Chicken',
    hardHint: 'Clay Oven',
  },
  {
    category: 'Indian Food',
    word: 'Masala Chai',
    easyHint: 'Cutting Chai',
    mediumHint: 'Spiced Tea',
    hardHint: 'Cardamom Brew',
  },
  {
    category: 'Indian Food',
    word: 'Rogan Josh',
    easyHint: 'Nihari',
    mediumHint: 'Kashmiri Lamb Curry',
    hardHint: 'Red Oil Stew',
  },
  {
    category: 'Indian Food',
    word: 'Pav Bhaji',
    easyHint: 'Vada Pav',
    mediumHint: 'Mumbai Mashed Veggie Dish',
    hardHint: 'Butter Tawa',
  },
  {
    category: 'Indian Food',
    word: 'Dal Makhani',
    easyHint: 'Dal Tadka',
    mediumHint: 'Creamy Black Lentil',
    hardHint: 'Overnight Simmer',
  },
  {
    category: 'Indian Food',
    word: 'Kachori',
    easyHint: 'Samosa',
    mediumHint: 'Stuffed Fried Pastry',
    hardHint: 'Rajasthani Breakfast',
  },
  {
    category: 'Indian Food',
    word: 'Rasmalai',
    easyHint: 'Rasgulla',
    mediumHint: 'Cream Soaked Sweet',
    hardHint: 'Saffron Milk Disc',
  },
  {
    category: 'Indian Food',
    word: 'Dhokla',
    easyHint: 'Khandvi',
    mediumHint: 'Gujarati Steamed Snack',
    hardHint: 'Yellow Sponge',
  },
  {
    category: 'Indian Food',
    word: 'Kebab',
    easyHint: 'Seekh Kebab',
    mediumHint: 'Lucknowi Grilled Meat',
    hardHint: 'Skewered Minced',
  },
  {
    category: 'Indian Food',
    word: 'Aloo Paratha',
    easyHint: 'Gobi Paratha',
    mediumHint: 'Stuffed Flatbread',
    hardHint: 'Butter & Curd Breakfast',
  },
  {
    category: 'Indian Food',
    word: 'Kheer',
    easyHint: 'Payasam',
    mediumHint: 'Rice Pudding',
    hardHint: 'Festival Dessert',
  },
  {
    category: 'Indian Food',
    word: 'Fish Curry',
    easyHint: 'Prawn Masala',
    mediumHint: 'Coastal Spicy Dish',
    hardHint: 'Coconut & Kokum',
  },
  {
    category: 'Indian Food',
    word: 'Poha',
    easyHint: 'Upma',
    mediumHint: 'Flattened Rice Breakfast',
    hardHint: 'Indore Special',
  },

  // ===========================================================================
  // 5. CRICKET
  // ===========================================================================
  {
    category: 'Cricket',
    word: 'Virat Kohli',
    easyHint: 'King Kohli',
    mediumHint: 'Indian Chase Master',
    hardHint: 'Anushka\'s Husband',
  },
  {
    category: 'Cricket',
    word: 'Sachin Tendulkar',
    easyHint: 'Master Blaster',
    mediumHint: 'God of Cricket',
    hardHint: '100 Centuries',
  },
  {
    category: 'Cricket',
    word: 'MS Dhoni',
    easyHint: 'Captain Cool',
    mediumHint: 'Helicopter Shot',
    hardHint: 'Ranchi Wicketkeeper',
  },
  {
    category: 'Cricket',
    word: 'Six',
    easyHint: 'Four',
    mediumHint: 'Maximum',
    hardHint: 'Over The Boundary',
  },
  {
    category: 'Cricket',
    word: 'LBW',
    easyHint: 'Bowled',
    mediumHint: 'Leg Before Wicket',
    hardHint: 'Umpire Finger Up',
  },
  {
    category: 'Cricket',
    word: 'IPL',
    easyHint: 'T20 League',
    mediumHint: 'Indian Premier League',
    hardHint: 'Auction Drama',
  },
  {
    category: 'Cricket',
    word: 'Jasprit Bumrah',
    easyHint: 'Indian Fast Bowler',
    mediumHint: 'Yorker King',
    hardHint: 'Unusual Action',
  },
  {
    category: 'Cricket',
    word: 'Rohit Sharma',
    easyHint: 'Hitman',
    mediumHint: 'Mumbai Indian Captain',
    hardHint: 'Triple ODI Double Century',
  },
  {
    category: 'Cricket',
    word: 'Ashes',
    easyHint: 'England vs Australia',
    mediumHint: 'Historic Test Series',
    hardHint: 'Burnt Bails',
  },
  {
    category: 'Cricket',
    word: 'Googly',
    easyHint: 'Doosra',
    mediumHint: 'Spin Bowling Variation',
    hardHint: 'Wrong One',
  },
  {
    category: 'Cricket',
    word: 'Hat-trick',
    easyHint: 'Three Wickets',
    mediumHint: 'Three Consecutive',
    hardHint: 'Rare Achievement',
  },
  {
    category: 'Cricket',
    word: 'Wicketkeeper',
    easyHint: 'Gloves',
    mediumHint: 'Behind The Stumps',
    hardHint: 'Stumping Specialist',
  },
  {
    category: 'Cricket',
    word: 'Duckworth Lewis',
    easyHint: 'Rain Rule',
    mediumHint: 'Revised Target Method',
    hardHint: 'Par Score',
  },
  {
    category: 'Cricket',
    word: 'Century',
    easyHint: 'Hundred Runs',
    mediumHint: 'Bat Raised High',
    hardHint: 'Helmet Off Celebration',
  },
  {
    category: 'Cricket',
    word: 'Powerplay',
    easyHint: 'Fielding Restrictions',
    mediumHint: 'First Overs Advantage',
    hardHint: 'Inner Circle',
  },
  {
    category: 'Cricket',
    word: 'Chennai Super Kings',
    easyHint: 'CSK',
    mediumHint: 'Yellow Army',
    hardHint: 'Whistle Podu',
  },
  {
    category: 'Cricket',
    word: 'Kapil Dev',
    easyHint: '1983 World Cup',
    mediumHint: 'Haryana Hurricane',
    hardHint: 'Natwest Catch',
  },
  {
    category: 'Cricket',
    word: 'Boundary',
    easyHint: 'Rope',
    mediumHint: 'Edge of The Field',
    hardHint: 'Four Runs',
  },
  {
    category: 'Cricket',
    word: 'Third Umpire',
    easyHint: 'TV Replay',
    mediumHint: 'DRS Review',
    hardHint: 'Upstairs Decision',
  },
  {
    category: 'Cricket',
    word: 'Pitch',
    easyHint: 'Wicket',
    mediumHint: '22 Yards',
    hardHint: 'Cracks and Turn',
  },
  {
    category: 'Cricket',
    word: 'Duck',
    easyHint: 'Zero',
    mediumHint: 'Out Without Scoring',
    hardHint: 'Golden One',
  },
  {
    category: 'Cricket',
    word: 'Maiden Over',
    easyHint: 'Dot Ball Over',
    mediumHint: 'No Runs Conceded',
    hardHint: 'Six Dots',
  },
  {
    category: 'Cricket',
    word: 'Shane Warne',
    easyHint: 'Leg Spin Legend',
    mediumHint: 'Ball of the Century',
    hardHint: 'Blonde Australian',
  },

  // ===========================================================================
  // 6. FOOTBALL
  // ===========================================================================
  {
    category: 'Football',
    word: 'Lionel Messi',
    easyHint: 'Argentine GOAT',
    mediumHint: 'Barcelona Legend',
    hardHint: 'La Pulga',
  },
  {
    category: 'Football',
    word: 'Cristiano Ronaldo',
    easyHint: 'CR7',
    mediumHint: 'Portuguese Forward',
    hardHint: 'SIUUU Celebration',
  },
  {
    category: 'Football',
    word: 'Neymar',
    easyHint: 'Brazilian Star',
    mediumHint: 'PSG Forward',
    hardHint: 'Diving Expert',
  },
  {
    category: 'Football',
    word: 'Penalty',
    easyHint: 'Free Kick',
    mediumHint: 'Spot Kick',
    hardHint: 'Twelve Yards',
  },
  {
    category: 'Football',
    word: 'Offside',
    easyHint: 'Flag Raised',
    mediumHint: 'Behind Last Defender',
    hardHint: 'VAR Lines',
  },
  {
    category: 'Football',
    word: 'Hat-trick',
    easyHint: 'Three Goals',
    mediumHint: 'Match Ball Home',
    hardHint: 'Triple Strike',
  },
  {
    category: 'Football',
    word: 'World Cup',
    easyHint: 'FIFA Trophy',
    mediumHint: 'Every Four Years',
    hardHint: 'Golden Globe',
  },
  {
    category: 'Football',
    word: 'Champions League',
    easyHint: 'UCL',
    mediumHint: 'European Club Trophy',
    hardHint: 'Big Ears',
  },
  {
    category: 'Football',
    word: 'Kylian Mbappé',
    easyHint: 'French Speedster',
    mediumHint: 'PSG to Real Madrid',
    hardHint: 'Teenage World Cup Winner',
  },
  {
    category: 'Football',
    word: 'Erling Haaland',
    easyHint: 'Man City Striker',
    mediumHint: 'Norwegian Goal Machine',
    hardHint: 'Viking Giant',
  },
  {
    category: 'Football',
    word: 'Real Madrid',
    easyHint: 'Los Blancos',
    mediumHint: 'Santiago Bernabéu',
    hardHint: 'Royal White',
  },
  {
    category: 'Football',
    word: 'Barcelona',
    easyHint: 'Barça',
    mediumHint: 'Camp Nou',
    hardHint: 'Més Que Un Club',
  },
  {
    category: 'Football',
    word: 'Red Card',
    easyHint: 'Yellow Card',
    mediumHint: 'Sent Off',
    hardHint: 'Early Shower',
  },
  {
    category: 'Football',
    word: 'Corner Kick',
    easyHint: 'Goal Kick',
    mediumHint: 'Flag Kick',
    hardHint: 'Arc Delivery',
  },
  {
    category: 'Football',
    word: 'Goalkeeper',
    easyHint: 'Gloves',
    mediumHint: 'Last Line of Defence',
    hardHint: 'Number One',
  },
  {
    category: 'Football',
    word: 'Manchester United',
    easyHint: 'Red Devils',
    mediumHint: 'Old Trafford',
    hardHint: 'Theatre of Dreams',
  },
  {
    category: 'Football',
    word: 'Liverpool',
    easyHint: 'The Reds',
    mediumHint: 'Anfield',
    hardHint: 'You\'ll Never Walk Alone',
  },
  {
    category: 'Football',
    word: 'Zinedine Zidane',
    easyHint: 'Zizou',
    mediumHint: 'French Midfielder Legend',
    hardHint: 'Headbutt Final',
  },
  {
    category: 'Football',
    word: 'Diego Maradona',
    easyHint: 'Hand of God',
    mediumHint: 'Argentine Legend',
    hardHint: 'Napoli King',
  },
  {
    category: 'Football',
    word: 'Pelé',
    easyHint: 'Brazilian King',
    mediumHint: '1000 Goals',
    hardHint: 'Santos Legend',
  },
  {
    category: 'Football',
    word: 'VAR',
    easyHint: 'Video Replay',
    mediumHint: 'Video Assistant Referee',
    hardHint: 'Screen Check',
  },
  {
    category: 'Football',
    word: 'Sunil Chhetri',
    easyHint: 'Indian Football Captain',
    mediumHint: 'Bengaluru FC',
    hardHint: 'Third Highest International Goals',
  },
  {
    category: 'Football',
    word: 'Free Kick',
    easyHint: 'Penalty',
    mediumHint: 'Dead Ball Situation',
    hardHint: 'Wall Formation',
  },

  // ===========================================================================
  // 7. MARVEL / SUPERHEROES
  // ===========================================================================
  {
    category: 'Marvel/Superheroes',
    word: 'Iron Man',
    easyHint: 'Tony Stark',
    mediumHint: 'Arc Reactor',
    hardHint: 'I Am Inevitable Response',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Thor',
    easyHint: 'God of Thunder',
    mediumHint: 'Mjolnir',
    hardHint: 'Asgardian Prince',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Spider-Man',
    easyHint: 'Peter Parker',
    mediumHint: 'Web Slinger',
    hardHint: 'Queens Kid',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Black Panther',
    easyHint: 'T\'Challa',
    mediumHint: 'Wakanda King',
    hardHint: 'Vibranium Suit',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Captain America',
    easyHint: 'Steve Rogers',
    mediumHint: 'Super Soldier',
    hardHint: 'Frozen in Ice',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Hulk',
    easyHint: 'Bruce Banner',
    mediumHint: 'Green Giant',
    hardHint: 'Smash',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Thanos',
    easyHint: 'Infinity Gauntlet',
    mediumHint: 'Mad Titan',
    hardHint: 'Perfectly Balanced',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Doctor Strange',
    easyHint: 'Sorcerer Supreme',
    mediumHint: 'Time Stone',
    hardHint: 'Neurosurgeon Wizard',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Black Widow',
    easyHint: 'Natasha Romanoff',
    mediumHint: 'Russian Spy Avenger',
    hardHint: 'Red Room',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Groot',
    easyHint: 'Rocket\'s Partner',
    mediumHint: 'Tree Guardian',
    hardHint: 'Three Word Vocabulary',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Loki',
    easyHint: 'Thor\'s Brother',
    mediumHint: 'God of Mischief',
    hardHint: 'Adopted Frost Giant',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Deadpool',
    easyHint: 'Wade Wilson',
    mediumHint: 'Merc With A Mouth',
    hardHint: 'Fourth Wall Breaker',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Wolverine',
    easyHint: 'Logan',
    mediumHint: 'Adamantium Claws',
    hardHint: 'Healing Factor Mutant',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Wanda',
    easyHint: 'Scarlet Witch',
    mediumHint: 'Reality Warper',
    hardHint: 'Westview',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Avengers',
    easyHint: 'Earth\'s Mightiest',
    mediumHint: 'Superhero Team',
    hardHint: 'Assemble',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Batman',
    easyHint: 'Dark Knight',
    mediumHint: 'Gotham Vigilante',
    hardHint: 'Billionaire Orphan',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Superman',
    easyHint: 'Clark Kent',
    mediumHint: 'Man of Steel',
    hardHint: 'Kryptonite Weakness',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Wonder Woman',
    easyHint: 'Diana Prince',
    mediumHint: 'Amazon Warrior',
    hardHint: 'Lasso of Truth',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Guardians of the Galaxy',
    easyHint: 'Star-Lord\'s Team',
    mediumHint: 'Space Misfits',
    hardHint: 'Awesome Mix Tape',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Infinity Stones',
    easyHint: 'Thanos Collection',
    mediumHint: 'Six Cosmic Gems',
    hardHint: 'Snap Material',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Shang-Chi',
    easyHint: 'Ten Rings',
    mediumHint: 'Martial Arts Hero',
    hardHint: 'Bus Fight Scene',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Ant-Man',
    easyHint: 'Scott Lang',
    mediumHint: 'Shrinking Superhero',
    hardHint: 'Quantum Realm',
  },
  {
    category: 'Marvel/Superheroes',
    word: 'Vision',
    easyHint: 'Mind Stone Android',
    mediumHint: 'Wanda\'s Love',
    hardHint: 'Phasing Through Walls',
  },

  // ===========================================================================
  // 8. HOLLYWOOD MOVIES
  // ===========================================================================
  {
    category: 'Hollywood Movies',
    word: 'Titanic',
    easyHint: 'Jack and Rose',
    mediumHint: 'Sinking Ship',
    hardHint: 'Draw Me Like',
  },
  {
    category: 'Hollywood Movies',
    word: 'The Dark Knight',
    easyHint: 'Batman Begins Sequel',
    mediumHint: 'Joker vs Batman',
    hardHint: 'Why So Serious',
  },
  {
    category: 'Hollywood Movies',
    word: 'Inception',
    easyHint: 'Dream Within Dream',
    mediumHint: 'Leonardo DiCaprio Sci-Fi',
    hardHint: 'Spinning Top',
  },
  {
    category: 'Hollywood Movies',
    word: 'Avengers: Endgame',
    easyHint: 'Infinity War Sequel',
    mediumHint: 'Time Heist',
    hardHint: 'I Love You 3000',
  },
  {
    category: 'Hollywood Movies',
    word: 'The Shawshank Redemption',
    easyHint: 'Prison Drama',
    mediumHint: 'Morgan Freeman Narrator',
    hardHint: 'Tunnel Behind Poster',
  },
  {
    category: 'Hollywood Movies',
    word: 'Interstellar',
    easyHint: 'Space Exploration',
    mediumHint: 'Christopher Nolan Sci-Fi',
    hardHint: 'Murph',
  },
  {
    category: 'Hollywood Movies',
    word: 'The Lion King',
    easyHint: 'Simba',
    mediumHint: 'Disney African Savanna',
    hardHint: 'Hakuna Matata',
  },
  {
    category: 'Hollywood Movies',
    word: 'Jurassic Park',
    easyHint: 'Dinosaurs',
    mediumHint: 'Spielberg Theme Park',
    hardHint: 'Life Finds A Way',
  },
  {
    category: 'Hollywood Movies',
    word: 'Harry Potter',
    easyHint: 'Hogwarts',
    mediumHint: 'Boy Wizard',
    hardHint: 'Platform 9¾',
  },
  {
    category: 'Hollywood Movies',
    word: 'The Matrix',
    easyHint: 'Neo',
    mediumHint: 'Virtual Reality Dystopia',
    hardHint: 'Red or Blue Pill',
  },
  {
    category: 'Hollywood Movies',
    word: 'Forrest Gump',
    easyHint: 'Run Forrest Run',
    mediumHint: 'Tom Hanks Classic',
    hardHint: 'Box of Chocolates',
  },
  {
    category: 'Hollywood Movies',
    word: 'Star Wars',
    easyHint: 'Luke Skywalker',
    mediumHint: 'Lightsaber Galaxy',
    hardHint: 'I Am Your Father',
  },
  {
    category: 'Hollywood Movies',
    word: 'Frozen',
    easyHint: 'Elsa',
    mediumHint: 'Disney Ice Princess',
    hardHint: 'Let It Go',
  },
  {
    category: 'Hollywood Movies',
    word: 'The Godfather',
    easyHint: 'Corleone Family',
    mediumHint: 'Mafia Epic',
    hardHint: 'Offer He Can\'t Refuse',
  },
  {
    category: 'Hollywood Movies',
    word: 'Fast and Furious',
    easyHint: 'Vin Diesel Cars',
    mediumHint: 'Street Racing Franchise',
    hardHint: 'Family',
  },
  {
    category: 'Hollywood Movies',
    word: 'Joker',
    easyHint: 'Joaquin Phoenix Villain',
    mediumHint: 'Gotham Origin Story',
    hardHint: 'Stairs Dance',
  },
  {
    category: 'Hollywood Movies',
    word: 'Oppenheimer',
    easyHint: 'Atomic Bomb Movie',
    mediumHint: 'Nolan Biopic 2023',
    hardHint: 'Now I Am Death',
  },
  {
    category: 'Hollywood Movies',
    word: 'Barbie',
    easyHint: 'Margot Robbie Doll',
    mediumHint: 'Pink Movie 2023',
    hardHint: 'Kenough',
  },
  {
    category: 'Hollywood Movies',
    word: 'Top Gun',
    easyHint: 'Maverick',
    mediumHint: 'Tom Cruise Fighter Jet',
    hardHint: 'Highway to Danger Zone',
  },
  {
    category: 'Hollywood Movies',
    word: 'Fight Club',
    easyHint: 'Brad Pitt Underground',
    mediumHint: 'First Rule',
    hardHint: 'Tyler Durden',
  },
  {
    category: 'Hollywood Movies',
    word: 'Parasite',
    easyHint: 'Bong Joon-ho',
    mediumHint: 'Korean Oscar Winner',
    hardHint: 'Basement Secret',
  },
  {
    category: 'Hollywood Movies',
    word: 'The Avengers',
    easyHint: 'Marvel Team Up',
    mediumHint: 'Battle of New York',
    hardHint: 'Shawarma Scene',
  },
  {
    category: 'Hollywood Movies',
    word: 'John Wick',
    easyHint: 'Keanu Reeves Assassin',
    mediumHint: 'Dog Revenge',
    hardHint: 'Pencil',
  },

  // ===========================================================================
  // 9. ANIMALS
  // ===========================================================================
  {
    category: 'Animals',
    word: 'Tiger',
    easyHint: 'Lion',
    mediumHint: 'Striped Big Cat',
    hardHint: 'Bengal',
  },
  {
    category: 'Animals',
    word: 'Elephant',
    easyHint: 'Rhinoceros',
    mediumHint: 'Trunk Animal',
    hardHint: 'Never Forgets',
  },
  {
    category: 'Animals',
    word: 'Peacock',
    easyHint: 'National Bird of India',
    mediumHint: 'Colorful Tail Display',
    hardHint: 'Rain Dance',
  },
  {
    category: 'Animals',
    word: 'Dolphin',
    easyHint: 'Whale',
    mediumHint: 'Intelligent Sea Mammal',
    hardHint: 'Sonar Clicks',
  },
  {
    category: 'Animals',
    word: 'Penguin',
    easyHint: 'Arctic Bird',
    mediumHint: 'Tuxedo Bird',
    hardHint: 'Happy Feet',
  },
  {
    category: 'Animals',
    word: 'Chameleon',
    easyHint: 'Iguana',
    mediumHint: 'Color Changing Reptile',
    hardHint: 'Blending In',
  },
  {
    category: 'Animals',
    word: 'Cobra',
    easyHint: 'Viper',
    mediumHint: 'Hooded Snake',
    hardHint: 'Snake Charmer',
  },
  {
    category: 'Animals',
    word: 'Cheetah',
    easyHint: 'Leopard',
    mediumHint: 'Fastest Land Animal',
    hardHint: 'Tear Marks',
  },
  {
    category: 'Animals',
    word: 'Panda',
    easyHint: 'Bamboo Bear',
    mediumHint: 'Black and White Bear',
    hardHint: 'China Symbol',
  },
  {
    category: 'Animals',
    word: 'Eagle',
    easyHint: 'Hawk',
    mediumHint: 'Raptor Bird of Prey',
    hardHint: 'Sharp Vision',
  },
  {
    category: 'Animals',
    word: 'Crocodile',
    easyHint: 'Alligator',
    mediumHint: 'Swamp Reptile',
    hardHint: 'Fake Tears',
  },
  {
    category: 'Animals',
    word: 'Octopus',
    easyHint: 'Squid',
    mediumHint: 'Eight Arms Sea Creature',
    hardHint: 'Ink Defense',
  },
  {
    category: 'Animals',
    word: 'Flamingo',
    easyHint: 'Pelican',
    mediumHint: 'Pink Wading Bird',
    hardHint: 'One Leg Stand',
  },
  {
    category: 'Animals',
    word: 'Gorilla',
    easyHint: 'Chimpanzee',
    mediumHint: 'Chest Beating Primate',
    hardHint: 'Silverback',
  },
  {
    category: 'Animals',
    word: 'Shark',
    easyHint: 'Great White',
    mediumHint: 'Ocean Predator',
    hardHint: 'Fin Above Water',
  },
  {
    category: 'Animals',
    word: 'Butterfly',
    easyHint: 'Moth',
    mediumHint: 'Colorful Winged Insect',
    hardHint: 'Metamorphosis',
  },
  {
    category: 'Animals',
    word: 'Parrot',
    easyHint: 'Macaw',
    mediumHint: 'Talking Bird',
    hardHint: 'Polly Wants',
  },
  {
    category: 'Animals',
    word: 'Kangaroo',
    easyHint: 'Koala',
    mediumHint: 'Pouch Jumper',
    hardHint: 'Boxing Marsupial',
  },
  {
    category: 'Animals',
    word: 'Owl',
    easyHint: 'Eagle',
    mediumHint: 'Nocturnal Hunter Bird',
    hardHint: '360 Head Turn',
  },
  {
    category: 'Animals',
    word: 'Camel',
    easyHint: 'Horse',
    mediumHint: 'Desert Ship',
    hardHint: 'Hump Water Storage',
  },
  {
    category: 'Animals',
    word: 'Jellyfish',
    easyHint: 'Starfish',
    mediumHint: 'Transparent Sea Creature',
    hardHint: 'Electric Sting',
  },
  {
    category: 'Animals',
    word: 'Tortoise',
    easyHint: 'Turtle',
    mediumHint: 'Slow Shelled Reptile',
    hardHint: 'Wins The Race',
  },
  {
    category: 'Animals',
    word: 'Wolf',
    easyHint: 'Fox',
    mediumHint: 'Pack Hunting Canine',
    hardHint: 'Moonlight Howl',
  },

  // ===========================================================================
  // 10. COUNTRIES
  // ===========================================================================
  {
    category: 'Countries',
    word: 'India',
    easyHint: 'Pakistan',
    mediumHint: 'Taj Mahal Country',
    hardHint: 'Spice Land',
  },
  {
    category: 'Countries',
    word: 'Japan',
    easyHint: 'China',
    mediumHint: 'Land of Rising Sun',
    hardHint: 'Cherry Blossoms',
  },
  {
    category: 'Countries',
    word: 'Brazil',
    easyHint: 'Argentina',
    mediumHint: 'Carnival Country',
    hardHint: 'Amazon Rainforest',
  },
  {
    category: 'Countries',
    word: 'Egypt',
    easyHint: 'Libya',
    mediumHint: 'Pyramid Nation',
    hardHint: 'Pharaoh Land',
  },
  {
    category: 'Countries',
    word: 'Australia',
    easyHint: 'New Zealand',
    mediumHint: 'Kangaroo Country',
    hardHint: 'Down Under',
  },
  {
    category: 'Countries',
    word: 'France',
    easyHint: 'Germany',
    mediumHint: 'Eiffel Tower Country',
    hardHint: 'Croissant Land',
  },
  {
    category: 'Countries',
    word: 'Italy',
    easyHint: 'Spain',
    mediumHint: 'Pizza Pasta Country',
    hardHint: 'Boot Shaped',
  },
  {
    category: 'Countries',
    word: 'USA',
    easyHint: 'Canada',
    mediumHint: 'Statue of Liberty',
    hardHint: 'Uncle Sam',
  },
  {
    category: 'Countries',
    word: 'Russia',
    easyHint: 'Ukraine',
    mediumHint: 'Largest Country',
    hardHint: 'Matryoshka Dolls',
  },
  {
    category: 'Countries',
    word: 'Switzerland',
    easyHint: 'Austria',
    mediumHint: 'Chocolate & Cheese',
    hardHint: 'Neutral Nation',
  },
  {
    category: 'Countries',
    word: 'South Korea',
    easyHint: 'North Korea',
    mediumHint: 'K-Pop Country',
    hardHint: 'Samsung Homeland',
  },
  {
    category: 'Countries',
    word: 'Thailand',
    easyHint: 'Vietnam',
    mediumHint: 'Land of Smiles',
    hardHint: 'Pad Thai',
  },
  {
    category: 'Countries',
    word: 'Mexico',
    easyHint: 'Colombia',
    mediumHint: 'Taco Country',
    hardHint: 'Day of the Dead',
  },
  {
    category: 'Countries',
    word: 'Greece',
    easyHint: 'Turkey',
    mediumHint: 'Olympic Origin',
    hardHint: 'Santorini Sunsets',
  },
  {
    category: 'Countries',
    word: 'Dubai',
    easyHint: 'Abu Dhabi',
    mediumHint: 'Burj Khalifa City',
    hardHint: 'Desert Oasis',
  },
  {
    category: 'Countries',
    word: 'Canada',
    easyHint: 'USA',
    mediumHint: 'Maple Leaf Country',
    hardHint: 'Polite People',
  },
  {
    category: 'Countries',
    word: 'Sri Lanka',
    easyHint: 'Maldives',
    mediumHint: 'Pearl of Indian Ocean',
    hardHint: 'Ceylon Tea',
  },
  {
    category: 'Countries',
    word: 'England',
    easyHint: 'Scotland',
    mediumHint: 'Big Ben Country',
    hardHint: 'Fish and Chips',
  },
  {
    category: 'Countries',
    word: 'Singapore',
    easyHint: 'Malaysia',
    mediumHint: 'Lion City',
    hardHint: 'No Chewing Gum',
  },
  {
    category: 'Countries',
    word: 'Nepal',
    easyHint: 'Bhutan',
    mediumHint: 'Everest Country',
    hardHint: 'Non-Rectangular Flag',
  },
  {
    category: 'Countries',
    word: 'Kenya',
    easyHint: 'Tanzania',
    mediumHint: 'Safari Country',
    hardHint: 'Marathon Runners',
  },

  // ===========================================================================
  // 11. INDIAN CITIES
  // ===========================================================================
  {
    category: 'Indian Cities',
    word: 'Mumbai',
    easyHint: 'Bombay',
    mediumHint: 'City of Dreams',
    hardHint: 'Dabbawalas',
  },
  {
    category: 'Indian Cities',
    word: 'Delhi',
    easyHint: 'New Delhi',
    mediumHint: 'Capital City',
    hardHint: 'Red Fort',
  },
  {
    category: 'Indian Cities',
    word: 'Jaipur',
    easyHint: 'Jodhpur',
    mediumHint: 'Pink City',
    hardHint: 'Hawa Mahal',
  },
  {
    category: 'Indian Cities',
    word: 'Varanasi',
    easyHint: 'Haridwar',
    mediumHint: 'Holy City on Ganges',
    hardHint: 'Oldest Living City',
  },
  {
    category: 'Indian Cities',
    word: 'Bangalore',
    easyHint: 'Hyderabad',
    mediumHint: 'IT Capital',
    hardHint: 'Garden City',
  },
  {
    category: 'Indian Cities',
    word: 'Kolkata',
    easyHint: 'Calcutta',
    mediumHint: 'City of Joy',
    hardHint: 'Howrah Bridge',
  },
  {
    category: 'Indian Cities',
    word: 'Chennai',
    easyHint: 'Madras',
    mediumHint: 'Detroit of India',
    hardHint: 'Marina Beach',
  },
  {
    category: 'Indian Cities',
    word: 'Hyderabad',
    easyHint: 'Secunderabad',
    mediumHint: 'City of Pearls',
    hardHint: 'Charminar',
  },
  {
    category: 'Indian Cities',
    word: 'Goa',
    easyHint: 'Beach Destination',
    mediumHint: 'Party Capital',
    hardHint: 'Portuguese Influence',
  },
  {
    category: 'Indian Cities',
    word: 'Agra',
    easyHint: 'Taj Mahal City',
    mediumHint: 'Mughal Heritage',
    hardHint: 'Petha Sweet',
  },
  {
    category: 'Indian Cities',
    word: 'Lucknow',
    easyHint: 'Kanpur',
    mediumHint: 'City of Nawabs',
    hardHint: 'Tunday Kebab',
  },
  {
    category: 'Indian Cities',
    word: 'Ahmedabad',
    easyHint: 'Surat',
    mediumHint: 'Gujarat\'s Largest City',
    hardHint: 'Sabarmati Ashram',
  },
  {
    category: 'Indian Cities',
    word: 'Pune',
    easyHint: 'Mumbai Neighbor',
    mediumHint: 'Oxford of the East',
    hardHint: 'Shaniwar Wada',
  },
  {
    category: 'Indian Cities',
    word: 'Amritsar',
    easyHint: 'Golden Temple City',
    mediumHint: 'Punjab Holy City',
    hardHint: 'Jallianwala Bagh',
  },
  {
    category: 'Indian Cities',
    word: 'Udaipur',
    easyHint: 'Jodhpur',
    mediumHint: 'City of Lakes',
    hardHint: 'Venice of the East',
  },
  {
    category: 'Indian Cities',
    word: 'Shimla',
    easyHint: 'Manali',
    mediumHint: 'Hill Station Capital',
    hardHint: 'British Summer Capital',
  },
  {
    category: 'Indian Cities',
    word: 'Darjeeling',
    easyHint: 'Gangtok',
    mediumHint: 'Tea Garden Town',
    hardHint: 'Toy Train',
  },
  {
    category: 'Indian Cities',
    word: 'Kochi',
    easyHint: 'Trivandrum',
    mediumHint: 'Queen of Arabian Sea',
    hardHint: 'Chinese Fishing Nets',
  },
  {
    category: 'Indian Cities',
    word: 'Mysore',
    easyHint: 'Bangalore Neighbor',
    mediumHint: 'Palace City',
    hardHint: 'Dasara Festival',
  },
  {
    category: 'Indian Cities',
    word: 'Rishikesh',
    easyHint: 'Haridwar',
    mediumHint: 'Yoga Capital',
    hardHint: 'Beatles Ashram',
  },
  {
    category: 'Indian Cities',
    word: 'Chandigarh',
    easyHint: 'Mohali',
    mediumHint: 'Planned City',
    hardHint: 'Le Corbusier Design',
  },
  {
    category: 'Indian Cities',
    word: 'Srinagar',
    easyHint: 'Jammu',
    mediumHint: 'Dal Lake City',
    hardHint: 'Houseboat Paradise',
  },

  // ===========================================================================
  // 12. TECHNOLOGY
  // ===========================================================================
  {
    category: 'Technology',
    word: 'iPhone',
    easyHint: 'Samsung Galaxy',
    mediumHint: 'Apple Smartphone',
    hardHint: 'Notch Design',
  },
  {
    category: 'Technology',
    word: 'Google',
    easyHint: 'Bing',
    mediumHint: 'Search Engine Giant',
    hardHint: 'I\'m Feeling Lucky',
  },
  {
    category: 'Technology',
    word: 'ChatGPT',
    easyHint: 'AI Chatbot',
    mediumHint: 'OpenAI Product',
    hardHint: 'Prompt Engineering',
  },
  {
    category: 'Technology',
    word: 'Instagram',
    easyHint: 'Snapchat',
    mediumHint: 'Photo Sharing App',
    hardHint: 'Reels',
  },
  {
    category: 'Technology',
    word: 'Tesla',
    easyHint: 'Electric Car',
    mediumHint: 'Elon Musk Company',
    hardHint: 'Autopilot',
  },
  {
    category: 'Technology',
    word: 'Netflix',
    easyHint: 'Amazon Prime Video',
    mediumHint: 'Streaming Platform',
    hardHint: 'Are You Still Watching?',
  },
  {
    category: 'Technology',
    word: 'WhatsApp',
    easyHint: 'Telegram',
    mediumHint: 'Green Messaging App',
    hardHint: 'Blue Ticks',
  },
  {
    category: 'Technology',
    word: 'YouTube',
    easyHint: 'Twitch',
    mediumHint: 'Video Streaming Platform',
    hardHint: 'Play Button Trophy',
  },
  {
    category: 'Technology',
    word: 'Bitcoin',
    easyHint: 'Ethereum',
    mediumHint: 'Cryptocurrency',
    hardHint: 'Satoshi Nakamoto',
  },
  {
    category: 'Technology',
    word: 'PlayStation',
    easyHint: 'Xbox',
    mediumHint: 'Sony Gaming Console',
    hardHint: 'Triangle Circle Cross Square',
  },
  {
    category: 'Technology',
    word: 'Alexa',
    easyHint: 'Siri',
    mediumHint: 'Amazon Voice Assistant',
    hardHint: 'Echo Speaker',
  },
  {
    category: 'Technology',
    word: 'TikTok',
    easyHint: 'Instagram Reels',
    mediumHint: 'Short Video App',
    hardHint: 'For You Page',
  },
  {
    category: 'Technology',
    word: 'Spotify',
    easyHint: 'Apple Music',
    mediumHint: 'Music Streaming',
    hardHint: 'Wrapped',
  },
  {
    category: 'Technology',
    word: 'Wi-Fi',
    easyHint: 'Bluetooth',
    mediumHint: 'Wireless Internet',
    hardHint: 'Password Please',
  },
  {
    category: 'Technology',
    word: 'Drone',
    easyHint: 'RC Helicopter',
    mediumHint: 'Flying Camera',
    hardHint: 'Quadcopter',
  },
  {
    category: 'Technology',
    word: 'VPN',
    easyHint: 'Proxy',
    mediumHint: 'Virtual Private Network',
    hardHint: 'Location Spoofer',
  },
  {
    category: 'Technology',
    word: 'Uber',
    easyHint: 'Ola',
    mediumHint: 'Ride Hailing App',
    hardHint: 'Surge Pricing',
  },
  {
    category: 'Technology',
    word: 'AirPods',
    easyHint: 'EarBuds',
    mediumHint: 'Apple Wireless Earphones',
    hardHint: 'White Stems',
  },
  {
    category: 'Technology',
    word: 'Zoom',
    easyHint: 'Google Meet',
    mediumHint: 'Video Calling App',
    hardHint: 'You\'re On Mute',
  },
  {
    category: 'Technology',
    word: 'GoPro',
    easyHint: 'Action Camera',
    mediumHint: 'Extreme Sports Camera',
    hardHint: 'Helmet Mount',
  },
  {
    category: 'Technology',
    word: 'Swiggy',
    easyHint: 'Zomato',
    mediumHint: 'Food Delivery App',
    hardHint: 'Orange Riders',
  },
  {
    category: 'Technology',
    word: 'Nintendo Switch',
    easyHint: 'PlayStation Portable',
    mediumHint: 'Handheld Console',
    hardHint: 'Joy-Con Controllers',
  },

  // ===========================================================================
  // 13. FAMOUS PEOPLE
  // ===========================================================================
  {
    category: 'Famous People',
    word: 'Elon Musk',
    easyHint: 'Jeff Bezos',
    mediumHint: 'Tesla SpaceX CEO',
    hardHint: 'Mars Obsession',
  },
  {
    category: 'Famous People',
    word: 'Narendra Modi',
    easyHint: 'Indian PM',
    mediumHint: 'Gujarat Chief Minister',
    hardHint: 'Mann Ki Baat',
  },
  {
    category: 'Famous People',
    word: 'Mahatma Gandhi',
    easyHint: 'Father of the Nation',
    mediumHint: 'Non-Violence Leader',
    hardHint: 'Salt March',
  },
  {
    category: 'Famous People',
    word: 'Taylor Swift',
    easyHint: 'Pop Star',
    mediumHint: 'Eras Tour',
    hardHint: 'Friendship Bracelets',
  },
  {
    category: 'Famous People',
    word: 'Albert Einstein',
    easyHint: 'Isaac Newton',
    mediumHint: 'E=mc² Physicist',
    hardHint: 'Wild White Hair',
  },
  {
    category: 'Famous People',
    word: 'Steve Jobs',
    easyHint: 'Bill Gates',
    mediumHint: 'Apple Co-Founder',
    hardHint: 'One More Thing',
  },
  {
    category: 'Famous People',
    word: 'BTS',
    easyHint: 'BLACKPINK',
    mediumHint: 'K-Pop Boy Band',
    hardHint: 'Army Fandom',
  },
  {
    category: 'Famous People',
    word: 'Barack Obama',
    easyHint: 'Donald Trump',
    mediumHint: 'First Black US President',
    hardHint: 'Yes We Can',
  },
  {
    category: 'Famous People',
    word: 'Ratan Tata',
    easyHint: 'Mukesh Ambani',
    mediumHint: 'Indian Industrialist',
    hardHint: 'Nano Car Vision',
  },
  {
    category: 'Famous People',
    word: 'APJ Abdul Kalam',
    easyHint: 'Missile Man',
    mediumHint: 'People\'s President',
    hardHint: 'Wings of Fire',
  },
  {
    category: 'Famous People',
    word: 'Beyoncé',
    easyHint: 'Rihanna',
    mediumHint: 'Queen Bey',
    hardHint: 'Destiny\'s Child',
  },
  {
    category: 'Famous People',
    word: 'Mark Zuckerberg',
    easyHint: 'Jack Dorsey',
    mediumHint: 'Facebook Founder',
    hardHint: 'Grey T-Shirt',
  },
  {
    category: 'Famous People',
    word: 'Sundar Pichai',
    easyHint: 'Satya Nadella',
    mediumHint: 'Google CEO',
    hardHint: 'IIT Kharagpur Alumni',
  },
  {
    category: 'Famous People',
    word: 'Mother Teresa',
    easyHint: 'Saint of Calcutta',
    mediumHint: 'Missionaries of Charity',
    hardHint: 'Blue-Bordered White Saree',
  },
  {
    category: 'Famous People',
    word: 'Leonardo DiCaprio',
    easyHint: 'Brad Pitt',
    mediumHint: 'Titanic Actor',
    hardHint: 'Oscar Finally',
  },
  {
    category: 'Famous People',
    word: 'Malala Yousafzai',
    easyHint: 'Greta Thunberg',
    mediumHint: 'Education Activist',
    hardHint: 'Youngest Nobel Peace',
  },
  {
    category: 'Famous People',
    word: 'Michael Jackson',
    easyHint: 'King of Pop',
    mediumHint: 'Moonwalk',
    hardHint: 'Thriller Dance',
  },
  {
    category: 'Famous People',
    word: 'Oprah Winfrey',
    easyHint: 'Ellen DeGeneres',
    mediumHint: 'Talk Show Queen',
    hardHint: 'You Get A Car',
  },
  {
    category: 'Famous People',
    word: 'Jeff Bezos',
    easyHint: 'Elon Musk',
    mediumHint: 'Amazon Founder',
    hardHint: 'Bald Billionaire',
  },
  {
    category: 'Famous People',
    word: 'Dwayne Johnson',
    easyHint: 'The Rock',
    mediumHint: 'Wrestler Turned Actor',
    hardHint: 'Eyebrow Raise',
  },
  {
    category: 'Famous People',
    word: 'AR Rahman',
    easyHint: 'Ilaiyaraaja',
    mediumHint: 'Mozart of Madras',
    hardHint: 'Roja Composer',
  },

  // ===========================================================================
  // 14. TV SHOWS
  // ===========================================================================
  {
    category: 'TV Shows',
    word: 'Sacred Games',
    easyHint: 'Mirzapur',
    mediumHint: 'Netflix India Crime',
    hardHint: 'Kabhi Kabhi Lagta Hai',
  },
  {
    category: 'TV Shows',
    word: 'Mirzapur',
    easyHint: 'Sacred Games',
    mediumHint: 'UP Crime Drama',
    hardHint: 'Munna Bhaiya',
  },
  {
    category: 'TV Shows',
    word: 'Game of Thrones',
    easyHint: 'House of the Dragon',
    mediumHint: 'Iron Throne Fantasy',
    hardHint: 'Winter Is Coming',
  },
  {
    category: 'TV Shows',
    word: 'Breaking Bad',
    easyHint: 'Better Call Saul',
    mediumHint: 'Chemistry Teacher Drug Lord',
    hardHint: 'Say My Name',
  },
  {
    category: 'TV Shows',
    word: 'Stranger Things',
    easyHint: 'Eleven',
    mediumHint: '80s Supernatural Netflix',
    hardHint: 'Upside Down',
  },
  {
    category: 'TV Shows',
    word: 'Money Heist',
    easyHint: 'La Casa de Papel',
    mediumHint: 'Spanish Bank Robbery',
    hardHint: 'Bella Ciao',
  },
  {
    category: 'TV Shows',
    word: 'Friends',
    easyHint: 'How I Met Your Mother',
    mediumHint: 'NYC Sitcom Six',
    hardHint: 'Central Perk',
  },
  {
    category: 'TV Shows',
    word: 'Squid Game',
    easyHint: 'Alice in Borderland',
    mediumHint: 'Korean Survival Game',
    hardHint: 'Red Light Green Light',
  },
  {
    category: 'TV Shows',
    word: 'The Office',
    easyHint: 'Parks and Recreation',
    mediumHint: 'Mockumentary Workplace',
    hardHint: 'That\'s What She Said',
  },
  {
    category: 'TV Shows',
    word: 'Panchayat',
    easyHint: 'Kota Factory',
    mediumHint: 'Rural India Comedy',
    hardHint: 'Phulera Village',
  },
  {
    category: 'TV Shows',
    word: 'Taarak Mehta Ka Ooltah Chashmah',
    easyHint: 'TMKOC',
    mediumHint: 'Gokuldham Society',
    hardHint: 'Jethalal',
  },
  {
    category: 'TV Shows',
    word: 'CID',
    easyHint: 'Crime Patrol',
    mediumHint: 'Indian Crime Investigation',
    hardHint: 'Daya Darwaza Tod Do',
  },
  {
    category: 'TV Shows',
    word: 'Wednesday',
    easyHint: 'Addams Family',
    mediumHint: 'Tim Burton Netflix',
    hardHint: 'Jenna Ortega Dance',
  },
  {
    category: 'TV Shows',
    word: 'The Boys',
    easyHint: 'Invincible',
    mediumHint: 'Dark Superhero Satire',
    hardHint: 'Homelander',
  },
  {
    category: 'TV Shows',
    word: 'Narcos',
    easyHint: 'Ozark',
    mediumHint: 'Drug Cartel Netflix',
    hardHint: 'Pablo Escobar',
  },
  {
    category: 'TV Shows',
    word: 'Peaky Blinders',
    easyHint: 'Boardwalk Empire',
    mediumHint: 'British Gangster BBC',
    hardHint: 'Razor Cap',
  },
  {
    category: 'TV Shows',
    word: 'The Family Man',
    easyHint: 'Special Ops',
    mediumHint: 'Spy Thriller Series',
    hardHint: 'Srikant Tiwari',
  },
  {
    category: 'TV Shows',
    word: 'Dark',
    easyHint: 'Stranger Things',
    mediumHint: 'German Time Travel',
    hardHint: 'Winden Town',
  },
  {
    category: 'TV Shows',
    word: 'Kota Factory',
    easyHint: 'Panchayat',
    mediumHint: 'IIT Coaching Drama',
    hardHint: 'Black and White Show',
  },
  {
    category: 'TV Shows',
    word: 'Scam 1992',
    easyHint: 'The Big Bull',
    mediumHint: 'Stock Market Fraud',
    hardHint: 'Harshad Mehta',
  },
  {
    category: 'TV Shows',
    word: 'Sherlock',
    easyHint: 'Elementary',
    mediumHint: 'Benedict Cumberbatch Detective',
    hardHint: '221B Baker Street',
  },
  {
    category: 'TV Shows',
    word: 'The Crown',
    easyHint: 'Downton Abbey',
    mediumHint: 'British Royal Netflix',
    hardHint: 'Queen Elizabeth Drama',
  },

  // ===========================================================================
  // 15. BRANDS
  // ===========================================================================
  {
    category: 'Brands',
    word: 'Nike',
    easyHint: 'Adidas',
    mediumHint: 'Swoosh Logo',
    hardHint: 'Just Do It',
  },
  {
    category: 'Brands',
    word: 'Apple',
    easyHint: 'Samsung',
    mediumHint: 'Bitten Fruit Logo',
    hardHint: 'Think Different',
  },
  {
    category: 'Brands',
    word: 'Coca-Cola',
    easyHint: 'Pepsi',
    mediumHint: 'Red Soda Brand',
    hardHint: 'Secret Formula',
  },
  {
    category: 'Brands',
    word: 'McDonald\'s',
    easyHint: 'Burger King',
    mediumHint: 'Golden Arches',
    hardHint: 'I\'m Lovin\' It',
  },
  {
    category: 'Brands',
    word: 'Amul',
    easyHint: 'Mother Dairy',
    mediumHint: 'Utterly Butterly',
    hardHint: 'Polka Dot Girl',
  },
  {
    category: 'Brands',
    word: 'Zara',
    easyHint: 'H&M',
    mediumHint: 'Spanish Fast Fashion',
    hardHint: 'Inditex',
  },
  {
    category: 'Brands',
    word: 'IKEA',
    easyHint: 'Home Centre',
    mediumHint: 'Swedish Furniture',
    hardHint: 'Assembly Required',
  },
  {
    category: 'Brands',
    word: 'Amazon',
    easyHint: 'Flipkart',
    mediumHint: 'A to Z Shopping',
    hardHint: 'Smile Arrow',
  },
  {
    category: 'Brands',
    word: 'Starbucks',
    easyHint: 'Costa Coffee',
    mediumHint: 'Mermaid Logo Coffee',
    hardHint: 'Pumpkin Spice Latte',
  },
  {
    category: 'Brands',
    word: 'Maggi',
    easyHint: 'Yippee',
    mediumHint: '2 Minute Noodles',
    hardHint: 'Taste Bhi Health Bhi',
  },
  {
    category: 'Brands',
    word: 'BMW',
    easyHint: 'Mercedes',
    mediumHint: 'Bavarian Motor Works',
    hardHint: 'Kidney Grille',
  },
  {
    category: 'Brands',
    word: 'Gucci',
    easyHint: 'Louis Vuitton',
    mediumHint: 'Italian Luxury Fashion',
    hardHint: 'Double G Logo',
  },
  {
    category: 'Brands',
    word: 'Tata',
    easyHint: 'Reliance',
    mediumHint: 'Indian Conglomerate',
    hardHint: 'Salt To Steel',
  },
  {
    category: 'Brands',
    word: 'Red Bull',
    easyHint: 'Monster Energy',
    mediumHint: 'Energy Drink',
    hardHint: 'Gives You Wings',
  },
  {
    category: 'Brands',
    word: 'Lego',
    easyHint: 'Hot Wheels',
    mediumHint: 'Plastic Building Bricks',
    hardHint: 'Step On Pain',
  },
  {
    category: 'Brands',
    word: 'Parle-G',
    easyHint: 'Britannia',
    mediumHint: 'Glucose Biscuit',
    hardHint: 'Baby On The Pack',
  },
  {
    category: 'Brands',
    word: 'Rolex',
    easyHint: 'Omega',
    mediumHint: 'Swiss Luxury Watch',
    hardHint: 'Crown Logo',
  },
  {
    category: 'Brands',
    word: 'Ferrari',
    easyHint: 'Lamborghini',
    mediumHint: 'Italian Supercar',
    hardHint: 'Prancing Horse',
  },
  {
    category: 'Brands',
    word: 'Jio',
    easyHint: 'Airtel',
    mediumHint: 'Indian Telecom Giant',
    hardHint: 'Free Data Revolution',
  },
  {
    category: 'Brands',
    word: 'Disney',
    easyHint: 'Pixar',
    mediumHint: 'Magic Kingdom',
    hardHint: 'Mouse Ears',
  },
  {
    category: 'Brands',
    word: 'Cadbury',
    easyHint: 'Nestle',
    mediumHint: 'Dairy Milk Chocolate',
    hardHint: 'Kuch Meetha Ho Jaaye',
  },
  {
    category: 'Brands',
    word: 'Bata',
    easyHint: 'Liberty',
    mediumHint: 'Shoe Brand',
    hardHint: 'Price Ending In 99',
  },

  // ===========================================================================
  // 16. SPORTS
  // ===========================================================================
  {
    category: 'Sports',
    word: 'Badminton',
    easyHint: 'Tennis',
    mediumHint: 'Shuttlecock Game',
    hardHint: 'PV Sindhu',
  },
  {
    category: 'Sports',
    word: 'Chess',
    easyHint: 'Checkers',
    mediumHint: 'Board Game of Kings',
    hardHint: 'Checkmate',
  },
  {
    category: 'Sports',
    word: 'Tennis',
    easyHint: 'Badminton',
    mediumHint: 'Racket Court Sport',
    hardHint: 'Love Means Zero',
  },
  {
    category: 'Sports',
    word: 'Swimming',
    easyHint: 'Diving',
    mediumHint: 'Pool Sport',
    hardHint: 'Michael Phelps',
  },
  {
    category: 'Sports',
    word: 'Boxing',
    easyHint: 'Wrestling',
    mediumHint: 'Ring Fighting Sport',
    hardHint: 'Muhammad Ali',
  },
  {
    category: 'Sports',
    word: 'Hockey',
    easyHint: 'Cricket',
    mediumHint: 'India\'s National Game',
    hardHint: 'Dhyan Chand',
  },
  {
    category: 'Sports',
    word: 'Formula 1',
    easyHint: 'NASCAR',
    mediumHint: 'Grand Prix Racing',
    hardHint: 'Pit Stop',
  },
  {
    category: 'Sports',
    word: 'Basketball',
    easyHint: 'Volleyball',
    mediumHint: 'NBA',
    hardHint: 'Slam Dunk',
  },
  {
    category: 'Sports',
    word: 'Golf',
    easyHint: 'Polo',
    mediumHint: 'Hole in One Sport',
    hardHint: 'Tiger Woods',
  },
  {
    category: 'Sports',
    word: 'Kabaddi',
    easyHint: 'Kho Kho',
    mediumHint: 'Indian Contact Sport',
    hardHint: 'Raid and Hold Breath',
  },
  {
    category: 'Sports',
    word: 'Archery',
    easyHint: 'Shooting',
    mediumHint: 'Bow and Arrow Sport',
    hardHint: 'Bullseye',
  },
  {
    category: 'Sports',
    word: 'Marathon',
    easyHint: 'Sprint',
    mediumHint: '42 Kilometers Race',
    hardHint: 'Greek Messenger',
  },
  {
    category: 'Sports',
    word: 'Gymnastics',
    easyHint: 'Figure Skating',
    mediumHint: 'Floor Exercise Sport',
    hardHint: 'Simone Biles',
  },
  {
    category: 'Sports',
    word: 'Table Tennis',
    easyHint: 'Ping Pong',
    mediumHint: 'Small Racket Sport',
    hardHint: 'Forrest Gump Scene',
  },
  {
    category: 'Sports',
    word: 'Surfing',
    easyHint: 'Skateboarding',
    mediumHint: 'Wave Riding Sport',
    hardHint: 'Hang Ten',
  },
  {
    category: 'Sports',
    word: 'Wrestling',
    easyHint: 'Judo',
    mediumHint: 'Akhada Sport',
    hardHint: 'Sushil Kumar',
  },
  {
    category: 'Sports',
    word: 'Volleyball',
    easyHint: 'Basketball',
    mediumHint: 'Net Court Team Sport',
    hardHint: 'Beach Spike',
  },
  {
    category: 'Sports',
    word: 'Polo',
    easyHint: 'Horse Racing',
    mediumHint: 'Horse Mallet Sport',
    hardHint: 'Sport of Kings',
  },
  {
    category: 'Sports',
    word: 'Skating',
    easyHint: 'Skiing',
    mediumHint: 'Wheeled/Bladed Shoe Sport',
    hardHint: 'Ice Rink Glide',
  },
  {
    category: 'Sports',
    word: 'Fencing',
    easyHint: 'Kendo',
    mediumHint: 'Sword Fighting Sport',
    hardHint: 'En Garde',
  },
  {
    category: 'Sports',
    word: 'Weightlifting',
    easyHint: 'Powerlifting',
    mediumHint: 'Olympic Barbell Sport',
    hardHint: 'Mirabai Chanu',
  },

  // ===========================================================================
  // 17. COMMON OBJECTS
  // ===========================================================================
  {
    category: 'Common Objects',
    word: 'Umbrella',
    easyHint: 'Raincoat',
    mediumHint: 'Rain Protection',
    hardHint: 'Folding Canopy',
  },
  {
    category: 'Common Objects',
    word: 'Sunglasses',
    easyHint: 'Spectacles',
    mediumHint: 'Eye Shade',
    hardHint: 'UV Protection',
  },
  {
    category: 'Common Objects',
    word: 'Mirror',
    easyHint: 'Reflection',
    mediumHint: 'Glass Surface',
    hardHint: 'Snow White Object',
  },
  {
    category: 'Common Objects',
    word: 'Candle',
    easyHint: 'Lamp',
    mediumHint: 'Wax Light Source',
    hardHint: 'Birthday Wish',
  },
  {
    category: 'Common Objects',
    word: 'Key',
    easyHint: 'Lock',
    mediumHint: 'Door Opener',
    hardHint: 'Metal Teeth',
  },
  {
    category: 'Common Objects',
    word: 'Watch',
    easyHint: 'Clock',
    mediumHint: 'Wrist Time Teller',
    hardHint: 'Tick Tock',
  },
  {
    category: 'Common Objects',
    word: 'Wallet',
    easyHint: 'Purse',
    mediumHint: 'Pocket Money Holder',
    hardHint: 'Leather Fold',
  },
  {
    category: 'Common Objects',
    word: 'Pillow',
    easyHint: 'Blanket',
    mediumHint: 'Sleep Cushion',
    hardHint: 'Feather Stuffed',
  },
  {
    category: 'Common Objects',
    word: 'Scissors',
    easyHint: 'Knife',
    mediumHint: 'Cutting Tool',
    hardHint: 'Beats Paper',
  },
  {
    category: 'Common Objects',
    word: 'Toothbrush',
    easyHint: 'Toothpaste',
    mediumHint: 'Oral Hygiene Tool',
    hardHint: 'Morning First Pick',
  },
  {
    category: 'Common Objects',
    word: 'Remote Control',
    easyHint: 'TV Controller',
    mediumHint: 'Channel Changer',
    hardHint: 'Always Missing',
  },
  {
    category: 'Common Objects',
    word: 'Pen',
    easyHint: 'Pencil',
    mediumHint: 'Writing Instrument',
    hardHint: 'Mightier Than Sword',
  },
  {
    category: 'Common Objects',
    word: 'Backpack',
    easyHint: 'Suitcase',
    mediumHint: 'Shoulder Bag',
    hardHint: 'School Companion',
  },
  {
    category: 'Common Objects',
    word: 'Charger',
    easyHint: 'Cable',
    mediumHint: 'Phone Power Supply',
    hardHint: 'Low Battery Savior',
  },
  {
    category: 'Common Objects',
    word: 'Comb',
    easyHint: 'Brush',
    mediumHint: 'Hair Grooming Tool',
    hardHint: 'Teeth But Not Mouth',
  },
  {
    category: 'Common Objects',
    word: 'Lighter',
    easyHint: 'Matchbox',
    mediumHint: 'Fire Starter',
    hardHint: 'Pocket Flame',
  },
  {
    category: 'Common Objects',
    word: 'Headphones',
    easyHint: 'Earbuds',
    mediumHint: 'Music Listening Device',
    hardHint: 'Head Band Sound',
  },
  {
    category: 'Common Objects',
    word: 'Fridge',
    easyHint: 'Freezer',
    mediumHint: 'Cold Storage Appliance',
    hardHint: 'Midnight Snack Spot',
  },
  {
    category: 'Common Objects',
    word: 'Ladder',
    easyHint: 'Stairs',
    mediumHint: 'Climbing Equipment',
    hardHint: 'Step By Step Up',
  },
  {
    category: 'Common Objects',
    word: 'Doorbell',
    easyHint: 'Door Knocker',
    mediumHint: 'Visitor Alert',
    hardHint: 'Ding Dong',
  },
  {
    category: 'Common Objects',
    word: 'Calendar',
    easyHint: 'Diary',
    mediumHint: 'Date Tracker',
    hardHint: 'Wall Grid',
  },
  {
    category: 'Common Objects',
    word: 'Stapler',
    easyHint: 'Paper Clip',
    mediumHint: 'Office Paper Joiner',
    hardHint: 'Metal Bite',
  },
  {
    category: 'Common Objects',
    word: 'Thermos',
    easyHint: 'Water Bottle',
    mediumHint: 'Hot Liquid Container',
    hardHint: 'Vacuum Insulated',
  },
  {
    category: 'Common Objects',
    word: 'Eraser',
    easyHint: 'Pencil',
    mediumHint: 'Mistake Remover',
    hardHint: 'Rubber Disappearer',
  },
];
